download/doc: fixed syntax to allow page being rendered
currently https://<instance>/download/doc fails with the error:
    undefined method `-' for "To customize the theming of the download
    page, you have multiple options to change the colors.
    ":ActiveSupport::SafeBuffer Did you mean? -@
this commit addresses this flaw by putting the rendered markdown in its
own seperate span, because the parser has seemingly issues with
multiline-haml (avoiding multiline in the first string [To customize..]
is an alternative solution that would also fix it).